### ISSUE TITLE
Conditions in github actions

### ISSUE THREAD

**Issue by ukorvl** [ukorvl/lightweight-charts-react-components#7]
Conditions in GitHub actions seems not to work and always return true.
For instance,
```
inputs:
      deploy-examples:
        description: "Deploy the examples to GitHub Pages"
        required: false
        default: true
        type: boolean

if: ${{ github.event.inputs.deploy-examples }}
```
It always runs, even if i set input false in the GitHub UI.
Though input is of type boolean, i suggest that GitHub stores the value as a string, which is always true, because it is not empty but "true" or "false".

The same problem we have for `build.yaml` action for `Lint commits` step.
